In [1]:
!pip install pyspark

Collecting pyspark
  Downloading pyspark-3.3.0.tar.gz (281.3 MB)
Collecting py4j==0.10.9.5
  Downloading py4j-0.10.9.5-py2.py3-none-any.whl (199 kB)
Building wheels for collected packages: pyspark

WARNING: Ignoring invalid distribution -mpy (c:\users\t-sarthak\anaconda3\lib\site-packages)

  Building wheel for pyspark (setup.py): started
  Building wheel for pyspark (setup.py): finished with status 'done'
  Created wheel for pyspark: filename=pyspark-3.3.0-py2.py3-none-any.whl size=281764026 sha256=f7f5546d577f76ad68579840f9b75b5656c4c8f172c5a8ba2758122d04298f3d
  Stored in directory: c:\users\t-sarthak\appdata\local\pip\cache\wheels\1d\27\68\1382001655ef41217e1dd34d59aa777612135379bab64279e9
Successfully built pyspark
Installing collected packages: py4j, pyspark
Successfully installed py4j-0.10.9.5 pyspark-3.3.0

WARNING: Ignoring invalid distribution -umpy (c:\users\t-sarthak\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\users\t-sarthak\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -mpy (c:\users\t-sarthak\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\t-sarthak\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\users\t-sarthak\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -mpy (c:\users\t-sarthak\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\t-sarthak\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\users\t-sarthak\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -mpy (c:\users\t-sarthak\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\t-sarthak\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\users\t-sarthak\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -mpy (c:\users\t-sarthak\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\t-sarthak\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\users\t-sarthak\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -mpy (c:\users\t-sarthak\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\t-sarthak\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\users\t-sarthak\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -mpy (c:\users\t-sarthak\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\t-sarthak\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\users\t-sarthak\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -mpy (c:\users\t-sarthak\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\t-sarthak\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\users\t-sarthak\anaconda3\lib\site-packages)

In [2]:
import pyspark

In [4]:
from pyspark.sql import SparkSession
spark=SparkSession.builder.appName("Practise").getOrCreate()

In [9]:
df=spark.read.csv("train.csv",header= True, inferSchema=True)

In [10]:
df.na.drop()

DataFrame[_c0: string, Delivery_person_ID: string, Delivery_person_Age: int, Delivery_person_Ratings: double, Restaurant_latitude: double, Restaurant_longitude: double, Delivery_location_latitude: double, Delivery_location_longitude: double, Time_Orderd: string, Time_Order_picked: string, Vehicle_condition: int, Type_of_order: string, multiple_deliveries: int, Festival: string, Time_taken: int]

In [11]:
df.show()

+------+------------------+-------------------+-----------------------+-------------------+--------------------+--------------------------+---------------------------+-----------+-----------------+-----------------+-------------+-------------------+--------+----------+
|   _c0|Delivery_person_ID|Delivery_person_Age|Delivery_person_Ratings|Restaurant_latitude|Restaurant_longitude|Delivery_location_latitude|Delivery_location_longitude|Time_Orderd|Time_Order_picked|Vehicle_condition|Type_of_order|multiple_deliveries|Festival|Time_taken|
+------+------------------+-------------------+-----------------------+-------------------+--------------------+--------------------------+---------------------------+-----------+-----------------+-----------------+-------------+-------------------+--------+----------+
|0x4607|    INDORES13DEL02|                 37|                    4.9|          22.745049|           75.892471|                 22.765049|                  75.912471|      11:30|            11:45|                2|        Snack|                  0|      No|        24|
|0xb379|    BANGRES18DEL02|                 34|                    4.5|          12.913041|           77.683237|                 13.043041|                  77.813237|      19:45|            19:50|                2|        Snack|                  1|      No|        33|
|0x5d6d|    BANGRES19DEL01|                 23|                    4.4|          12.914264|             77.6784|                 12.924264|                    77.6884|      08:30|            08:45|                0|       Drinks|                  1|      No|        26|
|0x7a6a|   COIMBRES13DEL02|                 38|                    4.7|          11.003669|           76.976494|                 11.053669|                  77.026494|       0.75|            18:10|                0|       Buffet|                  1|      No|        21|
|0x70a2|    CHENRES12DEL01|                 32|                    4.6|          12.972793|           80.249982|                 13.012793|                  80.289982|      13:30|            13:45|                1|        Snack|                  1|      No|        30|
|0x9bb4|     HYDRES09DEL03|                 22|                    4.8|          17.431668|           78.408321|                 17.461668|                  78.438321|      21:20|            21:30|                0|       Buffet|                  1|      No|        26|
|0x95b4|  RANCHIRES15DEL01|                 33|                    4.7|          23.369746|            85.33982|                 23.479746|                   85.44982|      19:15|            19:30|                1|         Meal|                  1|      No|        40|
|0x9eb2|     MYSRES15DEL02|                 35|                    4.6|          12.352058|            76.60665|                 12.482058|                   76.73665|      17:25|            17:30|                2|         Meal|                  1|      No|        32|
|0x1102|     HYDRES05DEL02|                 22|                    4.8|          17.433809|           78.386744|                 17.563809|                  78.516744|      20:55|            21:05|                0|       Buffet|                  1|      No|        34|
|0xcdcd|     DEHRES17DEL01|                 36|                    4.2|          30.327968|           78.046106|                 30.397968|                  78.116106|      21:55|            22:10|                2|        Snack|                  3|      No|        46|
|0xd987|     KOCRES16DEL01|                 21|                    4.7|          10.003064|           76.307589|                 10.043064|                  76.347589|      14:55|            15:05|                1|         Meal|                  1|      No|        23|
|0x2784|    PUNERES13DEL03|                 23|                    4.7|           18.56245|           73.916619|                  18.65245|                  74.006619|      17:30|            17:40|                1|       Drinks|                  1|      No|        21|
|0xc8b6|    LUDHRES15DEL02|                 34|                    4.3|          30.899584|           75.809346|                 30.919584|                  75.829346|      09:20|            09:30|                0|       Buffet|                  0|      No|        20|
|0xdb64|     KNPRES14DEL02|                 24|                    4.7|          26.463504|           80.372929|                 26.593504|                  80.502929|      19:50|            20:05|                1|        Snack|                  1|      No|        41|
|0x3af3|     MUMRES15DEL03|                 29|                    4.5|          19.176269|           72.836721|                 19.266269|                  72.926721|      20:25|            20:35|                2|       Buffet|                  1|      No|        20|
|0x3aab|     MYSRES01DEL01|                 35|                    4.0|          12.311072|           76.654878|                 12.351072|                  76.694878|      14:55|            15:10|                1|         Meal|                  1|      No|        33|
|0x689b|    PUNERES20DEL01|                 33|                    4.2|          18.592718|           73.773572|                 18.702718|                  73.883572|      20:30|            20:40|                2|        Snack|                  1|      No|        40|
|0x6f67|     HYDRES14DEL01|                 34|                    4.9|          17.426228|           78.407495|                 17.496228|                  78.477495|      20:40|            20:50|                0|        Snack|               null|      No|        41|
|0xc9cf|     KOLRES15DEL03|                 21|                    4.7|          22.552672|           88.352885|                 22.582672|                  88.382885|      21:15|            21:30|                0|         Meal|                  1|      No|        15|
|0x36b8|    PUNERES19DEL02|                 25|                    4.1|          18.563934|           73.915367|                 18.643935|                  73.995367|      20:20|            20:25|                0|        Snack|                  2|      No|        36|
+------+------------------+-------------------+-----------------------+-------------------+--------------------+--------------------------+---------------------------+-----------+-----------------+-----------------+-------------+-------------------+--------+----------+
only showing top 20 rows

In [12]:
import pandas as pd

In [14]:
df=pd.read_csv("train.csv")

In [21]:
df[df["Delivery_person_Age"]<24 or df["Delivery_person_Age"]<24]

,Unnamed: 0,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Time_Orderd,Time_Order_picked,Vehicle_condition,Type_of_order,multiple_deliveries,Festival,Time_taken
2,0x5d6d,BANGRES19DEL01,23.0,4.4,12.914264,77.678400,12.924264,77.688400,08:30,08:45,0,Drinks,1.0,No,26
5,0x9bb4,HYDRES09DEL03,22.0,4.8,17.431668,78.408321,17.461668,78.438321,21:20,21:30,0,Buffet,1.0,No,26
8,0x1102,HYDRES05DEL02,22.0,4.8,17.433809,78.386744,17.563809,78.516744,20:55,21:05,0,Buffet,1.0,No,34
10,0xd987,KOCRES16DEL01,21.0,4.7,10.003064,76.307589,10.043064,76.347589,14:55,15:05,1,Meal,1.0,No,23
11,0x2784,PUNERES13DEL03,23.0,4.7,18.562450,73.916619,18.652450,74.006619,17:30,17:40,1,Drinks,1.0,No,21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45574,0x90c5,MUMRES20DEL03,21.0,4.8,19.103249,72.846749,19.133249,72.876749,22:15,22:20,2,Drinks,0.0,No,22
45581,0x51f0,SURRES02DEL03,20.0,4.9,21.186608,72.794136,21.216608,72.824136,20:25,20:40,2,Drinks,1.0,No,18
45589,0xd641,AGRRES16DEL01,21.0,4.6,0.000000,0.000000,0.070000,0.070000,19:55,20:10,0,Buffet,1.0,No,36
45591,0x5eee,COIMBRES11DEL01,20.0,4.7,11.001753,76.986241,11.041753,77.026241,13:35,13:40,0,Snack,1.0,No,26
45592,0x5fb2,RANCHIRES09DEL02,23.0,4.9,23.351058,85.325731,23.431058,85.405731,17:10,17:15,2,Snack,1.0,No,36